apiversion: app/v1
kind: service
metadata:
  labels: 
    app: nodejs
    name: nodejs
spec:
  type: Nodeport
  ports:
    protocol: TCP
    port: 3000
    targetport: 3000
  selector:
      app: nodejs
  
    
